ALTER TABLE leads ADD COLUMN IF NOT EXISTS sale_price NUMERIC;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS commission_rate NUMERIC DEFAULT 2.5;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS agent_split NUMERIC DEFAULT 70;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS tax_rate NUMERIC DEFAULT 30;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS gross_commission NUMERIC;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS agent_gross NUMERIC;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS tax_amount NUMERIC;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS net_income NUMERIC;
